In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4,5]

In [3]:
my_array1 = np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4, 5])

In [5]:
my_list2 = [11,22,33,44]

In [62]:
my_lists = [my_list1, my_list2]

In [63]:
my_lists

[[1, 2, 3, 4, 5], [11, 22, 33, 44]]

In [68]:
my_array2 = np.array(my_lists)
my_array2Test = np.array([[1,2,3,4,5], [11,22,33,44,55]])

In [69]:
my_array2
my_array2Test

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [61]:
my_array2.shape

(2,)

In [44]:
np.size(my_array2)

2

In [19]:
my_array2.dtype

dtype('O')

In [32]:
ss = np.zeros(5)

In [23]:
my_zeros_array = np.zeros(5)

In [24]:
my_zeros_array.dtype

dtype('float64')

In [26]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [27]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [29]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [30]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [33]:
my_lists

[[1, 2, 3, 4, 5], [11, 22, 33, 44]]

In [37]:
len(my_lists[0])

5

In [45]:
test1 = [[1, 2, 3, 4, 5], [11, 22, 33, 44]]

In [49]:
array_test1 = np.array([[1, 2, 3, 4, 5], [11, 22, 33, 44]], np.int32)

ValueError: setting an array element with a sequence.

In [47]:
array_test1

array([[1, 2, 3, 4, 5], [11, 22, 33, 44]], dtype=object)