In [1]:
import pandas as pd
import numpy as np
from pandas import DataFrame, Series

In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1], axis = 1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [8]:
np.concatenate([arr1,arr1],axis = 0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
ser1 = Series([0,1,2],index = ['T','U','V'])

In [10]:
ser2 = Series([3,4],index=['X','Y'])
ser2

X    3
Y    4
dtype: int64

In [11]:
ser1

T    0
U    1
V    2
dtype: int64

In [12]:
ser2

X    3
Y    4
dtype: int64

In [14]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [15]:
pd.concat([ser1, ser2], axis = 1)

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [16]:
pd.concat([ser1, ser2], keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [17]:
dfram1 = DataFrame(np.random.randn(4,3), columns = ['X','Y','Z'])

In [18]:
dfram2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])

In [19]:
dfram1

X         Y         Z
0  0.219790  2.026853 -1.207303
1 -1.504454  0.494198 -0.234226
2 -0.476117 -2.666075 -0.826197
3 -1.747441  0.109321  0.247445

In [20]:
dfram2

Y         Q         X
0  0.263227  0.277104  0.250473
1 -0.813656 -0.504813 -1.147020
2  0.405595 -0.318841  0.190039

In [23]:
pd.concat([dfram1, dfram2])

Q         X         Y         Z
0       NaN  0.219790  2.026853 -1.207303
1       NaN -1.504454  0.494198 -0.234226
2       NaN -0.476117 -2.666075 -0.826197
3       NaN -1.747441  0.109321  0.247445
0  0.277104  0.250473  0.263227       NaN
1 -0.504813 -1.147020 -0.813656       NaN
2 -0.318841  0.190039  0.405595       NaN

In [24]:
pd.concat([dfram1, dfram2], ignore_index = True)

Q         X         Y         Z
0       NaN  0.219790  2.026853 -1.207303
1       NaN -1.504454  0.494198 -0.234226
2       NaN -0.476117 -2.666075 -0.826197
3       NaN -1.747441  0.109321  0.247445
4  0.277104  0.250473  0.263227       NaN
5 -0.504813 -1.147020 -0.813656       NaN
6 -0.318841  0.190039  0.405595       NaN