In [4]:
import numpy as np
arr = np.arange(50)

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04,   5.98741417e+04,
         1.62754791e+05,   4.42413392e+05,   1.20260428e+06,
         3.26901737e+06,   8.88611052e+06,   2.41549528e+07,
         6.56599691e+07,   1.78482301e+08,   4.85165195e+08,
         1.31881573e+09,   3.58491285e+09,   9.74480345e+09,
         2.64891221e+10,   7.20048993e+10,   1.95729609e+11,
         5.32048241e+11,   1.44625706e+12,   3.93133430e+12,
         1.06864746e+13,   2.90488497e+13,   7.89629602e+13,
         2.14643580e+14,   5.83461743e+14,   1.58601345e+15,
         4.31123155e+15,   1.17191424e+16,   3.18559318e+16,
         8.65934004e+16,   2.35385267e+17,   6.39843494e+17,
         1.73927494e+18,   4.72783947e+18,   1.28516001e+19,
         3.49342711e+19,   9.49611942e+19,   2.58131289e+20,
         7.01673591e+20,

In [7]:
A = np.random.randn(10)
A

array([ 0.98083531,  1.31514925,  0.88556012,  1.19676121,  1.41037723,
       -1.30291714, -0.70180063,  0.82558302,  1.28793775, -3.55631394])

In [8]:
B = np.random.randn(10)

In [9]:
np.add(A,B)

array([ 1.43963241,  3.24126435,  1.15603992,  2.97188446,  2.51803621,
       -0.8426202 ,  1.2100073 , -0.45282323,  1.19655063, -2.94819978])

In [11]:
np.maximum(A,B)

array([ 0.98083531,  1.9261151 ,  0.88556012,  1.77512325,  1.41037723,
        0.46029695,  1.91180793,  0.82558302,  1.28793775,  0.60811416])

In [ ]:
website = ""
import webbrowser

webbrowser.open(website);